### ISSUE TITLE
gtksourceview ebuild breaks virt-manager

### ISSUE THREAD

**Issue by ishigoya** [ambasta/ambasta#4]
I installed `x11-libs/gtksourceview` from this overlay and virt-manager stopped working.

The underlying issue is detailed [here](https://bugzilla.opensuse.org/show_bug.cgi?id=1191356). Essentially, virt-manager depends on version 3 or 4 of gtksourceview. That is enforced in Gentoo by depending on `x11-libs/gtksourceview` in slot 4.

The ebuild in this overlay for version 5 of gtksourceview currently installs to slot 4, so it's treated in Gentoo as a valid dependency for virt-manager:

https://github.com/ambasta/ambasta/blob/c6b0791b94dc1465eec8001e76476a662ef8fd36/x11-libs/gtksourceview/gtksourceview-5.2.0.ebuild#L12

Could you amend the slot for this ebuild?

**Comment by ambasta** [comment]
Sorry, I missed the issue. Have removed the ebuild since its obsolete
